name: FastAPI CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip list  # ✅ List installed packages

      - name: Debug Python Version
        run: python --version && which python

      - name: Create .env file
        run: |
          echo "SMTP_SERVER=smtp.gmail.com" > .env
          echo "SMTP_PORT=587" >> .env
          echo "SMTP_USERNAME=gokulraja682001@gmail.com" >> .env
          echo "SMTP_PASSWORD=axta oymz hnpk zxoh" >> .env
          echo "SENDER_EMAIL=gokulraja682001@gmail.com" >> .env
          cat .env  # ✅ Debugging: Check if .env is created properly (will not expose secrets)

      - name: Start FastAPI Application with Logging
        run: |
          source venv/bin/activate
          uvicorn app.main:app --host 0.0.0.0 --port 8000 --log-level debug > fastapi.log 2>&1 &
          sleep 5
          cat fastapi.log  # ✅ Display logs

      - name: Check Running Processes
        run: ps aux | grep uvicorn

      - name: Check If Application Started Successfully
        run: |
          curl -v http://127.0.0.1:8000/ || (echo "FastAPI did not start!" && exit 1)

      - name: Stop Application
        run: pkill -f "uvicorn"
